import Head from "next/head";

const Home = () => {
  return (
    <div className="pt-28">
      <Head>
        <title className="">Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="mx-auto w-full md:w-3/5">top</div>
    </div>
  );
};

export default Home;
