import Head from "next/head";
import { useRouter } from "next/router";
import { Layout } from "src/components/Layout";
import styles from "src/styles/Home.module.css";
import { useGetUser } from "src/utils/hooks/useGetUser";

export default function Home() {
  const router = useRouter();
  const { getUserFn } = useGetUser();
  const handleClick = () => {
    getUserFn();
    router.push("/sakagura");
  };
  return (
    <div className={styles.container}>
      <Head>
        <title className="">Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="mx-auto w-11/12">
          <button
            className="w-full h-[60px] bg-red-600 rounded-lg"
            onClick={handleClick}
          >
            酒蔵に行く
          </button>
        </div>
      </Layout>
    </div>
  );
}
